"""
klayout_server.py  —  KLayout DRC HTTP service
─────────────────────────────────────────────────────────────────────────────
Tiny FastAPI server that:
  GET  /health        — liveness probe
  POST /run_drc       — run KLayout headless DRC
  GET  /viewer_url    — return noVNC URL for debug viewer

The /run_drc endpoint:
  1. Receives {oasis_path, script_path, report_path}
  2. Calls drc_runner.sh which invokes klayout -b (batch mode)
  3. Returns {status: ok} or {status: error, detail: ...}

Run:
  python3 klayout_server.py --port 8002
"""

import argparse
import asyncio
import logging
import os
import subprocess
from pathlib import Path

from fastapi import FastAPI
from pydantic import BaseModel
import uvicorn

logging.basicConfig(level=logging.INFO,
                    format="%(asctime)s  %(name)s  %(levelname)s  %(message)s")
logger = logging.getLogger("klayout-server")

app = FastAPI(title="KLayout DRC Service", version="1.0.0")

EDA_SHARE = os.getenv("EDA_SHARE", "/eda_share")
NOVNC_PORT = int(os.getenv("NOVNC_PORT", "6080"))
DRC_RUNNER = Path(__file__).parent / "drc_runner.sh"


class DRCRequest(BaseModel):
    oasis_path:  str
    script_path: str
    report_path: str


@app.get("/health")
async def health():
    return {"status": "ok"}


@app.get("/viewer_url")
async def viewer_url():
    # Return the noVNC URL based on the container's published port
    host = os.getenv("HOSTNAME", "localhost")
    return {"url": f"http://{host}:{NOVNC_PORT}/vnc.html"}


@app.post("/run_drc")
async def run_drc(req: DRCRequest):
    """
    Execute KLayout headless DRC.

    The DRC script (Ruby .drc file) was generated by drc_script_gen.py and
    written to /eda_share/drc_NNN.drc.  KLayout runs it in batch mode and
    writes the .rdb report to report_path.
    """
    logger.info("[DRC] Running: oasis=%s script=%s report=%s",
                req.oasis_path, req.script_path, req.report_path)

    # Validate inputs exist
    for path, name in [(req.oasis_path, "oasis_path"), (req.script_path, "script_path")]:
        if not Path(path).exists():
            return {"status": "error", "detail": f"{name} not found: {path}"}

    try:
        proc = await asyncio.create_subprocess_exec(
            "/usr/local/bin/drc_runner.sh",
            req.oasis_path,
            req.script_path,
            req.report_path,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=300.0)

        if proc.returncode != 0:
            err = stderr.decode(errors="replace").strip()
            logger.error("[DRC] KLayout exited %d: %s", proc.returncode, err[:500])
            return {"status": "error", "detail": err[:500]}

        logger.info("[DRC] Completed, report at %s", req.report_path)
        return {"status": "ok"}

    except asyncio.TimeoutError:
        logger.error("[DRC] Timed out after 300s")
        return {"status": "error", "detail": "DRC run timed out after 300s"}
    except Exception as e:
        logger.exception("[DRC] Unexpected error")
        return {"status": "error", "detail": str(e)}


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--port", type=int, default=8002)
    args = parser.parse_args()
    uvicorn.run(app, host="0.0.0.0", port=args.port, log_level="info")
