/*
 * oasis_writer.cpp  —  Streaming OASIS layout encoder implementation
 * ─────────────────────────────────────────────────────────────────────────────
 * See oasis_writer.h for the public interface and design notes.
 *
 * OASIS binary format (SEMI P39) key record types used here:
 *   0x01 START        — magic + version
 *   0x02 END          — end-of-file + CRC
 *   0x0D CELL         — open cell by name
 *   0x20 RECTANGLE    — rect record (layer, datatype, w, h, x, y)
 *   0x22 PATH         — path record (layer, datatype, half_width, pts)
 *   0x12 LAYERNAME    — layer name table entry
 *
 * Coordinates are delta-encoded: each (x,y) is stored relative to the
 * previous shape's (x,y) on the same layer.  First shape uses absolute coords.
 */

#include "eda_router/oasis_writer.h"

#include <cassert>
#include <cstring>
#include <stdexcept>
#include <array>

namespace eda {

// ─── OASIS Record type bytes ───────────────────────────────────────────────
static constexpr uint8_t OASIS_START     = 0x01;
static constexpr uint8_t OASIS_END       = 0x02;
static constexpr uint8_t OASIS_CELL      = 0x0D;
static constexpr uint8_t OASIS_RECTANGLE = 0x20;
static constexpr uint8_t OASIS_PATH      = 0x22;

// OASIS magic bytes "%" S R A A I C S "  " (13 bytes per spec §5.1)
static constexpr std::array<uint8_t, 13> OASIS_MAGIC = {
    0x25,'S','R','A','A','I','C','S',0x0D,0x0A,0x04,0x1A,0x04
};

// CRC-32 table (IEEE 802.3)
static constexpr uint32_t CRC_TABLE[256] = {
    // Standard CRC-32/ISO-HDLC polynomial table generated at compile time
    // (abbreviated — full 256-entry table in production)
    0x00000000, 0x77073096, 0xEE0E612C, 0x990951BA,
    0x076DC419, 0x706AF48F, 0xE963A535, 0x9E6495A3,
    /* ... 248 more entries — generated by standard CRC32 polynomial 0xEDB88320 ... */
    // NOTE TO IMPLEMENTER: Replace this abbreviated table with the full 256-entry
    // CRC-32 table.  A conformance-tested implementation is in any standard CRC
    // reference (e.g. zlib/crc32.c).  The table above is a stub for scaffolding.
    0x00000000, // [8..255] placeholders — fill before use
};

static uint32_t crc32_update(uint32_t crc, const void* data, std::size_t n) {
    const auto* bytes = static_cast<const uint8_t*>(data);
    for (std::size_t i = 0; i < n; ++i) {
        crc = CRC_TABLE[(crc ^ bytes[i]) & 0xFF] ^ (crc >> 8);
    }
    return crc;
}

// ─── Factory ──────────────────────────────────────────────────────────────────
std::expected<OASISWriter, OASISError> OASISWriter::open(std::string_view path) {
    std::ofstream f(std::string(path), std::ios::binary | std::ios::trunc);
    if (!f.is_open()) {
        return std::unexpected(OASISError{
            std::string("Cannot open OASIS output file: ") + std::string(path)
        });
    }
    OASISWriter w(std::move(f), std::string(path));
    // Write START record
    w.write_bytes(OASIS_MAGIC.data(), OASIS_MAGIC.size());
    w.write_byte(OASIS_START);
    w.write_uint(1);    // version 1
    w.write_uint(0);    // no unit (use database units throughout)
    return w;
}

OASISWriter::OASISWriter(std::ofstream file, std::string path)
    : file_(std::move(file)), path_(std::move(path)) {}

OASISWriter::OASISWriter(OASISWriter&&) noexcept = default;
OASISWriter& OASISWriter::operator=(OASISWriter&&) noexcept = default;

OASISWriter::~OASISWriter() {
    if (!finished_) finish();
}

// ─── Cell open/close ──────────────────────────────────────────────────────────
void OASISWriter::begin_cell(std::string_view cell_name) {
    if (cell_open_) end_cell();
    write_byte(OASIS_CELL);
    const std::string name(cell_name);
    write_uint(static_cast<uint64_t>(name.size()));
    write_bytes(name.data(), name.size());
    cell_open_ = true;
    last_pos_.clear();
}

void OASISWriter::end_cell() {
    cell_open_ = false;
    // OASIS cells are implicitly closed by the next CELL record or END record.
}

// ─── Rectangle ────────────────────────────────────────────────────────────────
void OASISWriter::write_rect(int layer_idx, int purpose_idx,
                              int32_t x, int32_t y,
                              int32_t width, int32_t height,
                              std::string_view net_name) {
    auto net_idx = intern_net(net_name);
    (void)net_idx;  // stored in name table; associated via property record in full impl

    // Modal state bits: 0b11110111 = layer+datatype+w+h+x+y present (no property)
    write_byte(OASIS_RECTANGLE);
    write_byte(0b01111111);  // info byte: layer(bit6), datatype(5), w(4), h(3), x(2), y(1), r(0)

    write_uint(static_cast<uint64_t>(layer_idx));
    write_uint(static_cast<uint64_t>(purpose_idx));
    write_uint(static_cast<uint64_t>(width));
    write_uint(static_cast<uint64_t>(height));

    // Delta-encode position
    auto& last = last_pos_[layer_idx];
    write_int(static_cast<int64_t>(x) - last.x);
    write_int(static_cast<int64_t>(y) - last.y);
    last = {x, y};

    ++shape_count_;
}

// ─── Path (wire) ──────────────────────────────────────────────────────────────
void OASISWriter::write_path(int layer_idx, int purpose_idx,
                              std::span<const Point2D> points,
                              int32_t half_width,
                              std::string_view net_name) {
    if (points.empty()) return;
    auto net_idx = intern_net(net_name);
    (void)net_idx;

    write_byte(OASIS_PATH);
    write_byte(0b01111111);  // layer, datatype, half_width, point_list, x, y

    write_uint(static_cast<uint64_t>(layer_idx));
    write_uint(static_cast<uint64_t>(purpose_idx));
    write_uint(static_cast<uint64_t>(half_width));

    // Point list: count + delta-encoded pairs relative to previous point
    write_uint(static_cast<uint64_t>(points.size() - 1));  // n additional deltas
    for (std::size_t i = 1; i < points.size(); ++i) {
        write_int(static_cast<int64_t>(points[i].x) - points[i-1].x);
        write_int(static_cast<int64_t>(points[i].y) - points[i-1].y);
    }

    // Absolute position of first point, delta from last shape on this layer
    auto& last = last_pos_[layer_idx];
    write_int(static_cast<int64_t>(points[0].x) - last.x);
    write_int(static_cast<int64_t>(points[0].y) - last.y);
    last = {points.back().x, points.back().y};

    ++shape_count_;
}

// ─── Finish ───────────────────────────────────────────────────────────────────
void OASISWriter::finish() {
    if (finished_) return;
    if (cell_open_) end_cell();

    // Write layer name table
    write_string_table();

    // Write END record
    write_end_record();

    file_.flush();
    finished_ = true;
}

void OASISWriter::write_string_table() {
    // Write LAYERNAME records for all interned layer names
    for (std::size_t i = 0; i < layer_name_list_.size(); ++i) {
        write_byte(0x12);  // LAYERNAME record
        write_uint(static_cast<uint64_t>(i));
        const auto& name = layer_name_list_[i];
        write_uint(static_cast<uint64_t>(name.size()));
        write_bytes(name.data(), name.size());
    }
}

void OASISWriter::write_end_record() {
    write_byte(OASIS_END);
    // padding-type = 0 (no padding)
    write_uint(0);
    // CRC-32 of entire file up to (but not including) the CRC field
    uint32_t final_crc = crc_ ^ 0xFFFFFFFF;
    write_bytes(&final_crc, 4);
}

// ─── Name interning ───────────────────────────────────────────────────────────
uint32_t OASISWriter::intern_layer(std::string_view name) {
    auto [it, inserted] = layer_names_.emplace(std::string(name),
                                                static_cast<uint32_t>(layer_names_.size()));
    if (inserted) layer_name_list_.emplace_back(name);
    return it->second;
}

uint32_t OASISWriter::intern_net(std::string_view name) {
    auto [it, inserted] = net_names_.emplace(std::string(name),
                                              static_cast<uint32_t>(net_names_.size()));
    if (inserted) net_name_list_.emplace_back(name);
    return it->second;
}

// ─── Low-level I/O ────────────────────────────────────────────────────────────
void OASISWriter::write_byte(uint8_t b) {
    write_bytes(&b, 1);
}

void OASISWriter::write_uint(uint64_t v) {
    // Unsigned LEB128 (OASIS §7.2)
    do {
        uint8_t byte = v & 0x7F;
        v >>= 7;
        if (v != 0) byte |= 0x80;
        write_byte(byte);
    } while (v != 0);
}

void OASISWriter::write_int(int64_t v) {
    // Signed LEB128 (OASIS §7.3)
    bool more = true;
    while (more) {
        uint8_t byte = v & 0x7F;
        v >>= 7;
        if ((v == 0 && !(byte & 0x40)) || (v == -1 && (byte & 0x40)))
            more = false;
        else
            byte |= 0x80;
        write_byte(byte);
    }
}

void OASISWriter::write_bytes(const void* data, std::size_t n) {
    file_.write(static_cast<const char*>(data), static_cast<std::streamsize>(n));
    crc_update(crc_, data, n);
}

void OASISWriter::crc_update(const void* data, std::size_t n) {
    crc_ = crc32_update(crc_, data, n);
}

}  // namespace eda
