"""
eu_compiler.py  —  EU (Execution Unit) template compiler
─────────────────────────────────────────────────────────────────────────────
Converts a Jinja2 EU template + runtime arguments into an executable script
string ready to be sent to the HEA via _hea_client.execute_eu().

TEMPLATE LOOKUP ORDER:
  1. eu_registry/{host}/{template_name}.{lang}.j2   (static registry)
  2. Dynamic template generated by script_synthesis.py (AI-generated)
     → only used when static template is missing AND RAG confidence is high

RENDERING:
  Jinja2 with strict undefined handling.  Any missing variable raises
  UndefinedError so problems are caught before deployment to the live EDA DB.

USAGE:
  from orchestrator.eu_compiler import compile_eu

  script = compile_eu(
      host="cadence_virtuoso",
      template_name="route_nets",
      args={"net_ids": [1, 2, 3], "undo_group": "eda_route_001"}
  )
  await execute_eu("route_nets_virtuoso", script, args)
"""

from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# Registry root: vlsi/agent/src/orchestrator/eu_registry/
_REGISTRY_ROOT = Path(__file__).parent / "eu_registry"

# Language extension map
_LANG_EXT: dict[str, str] = {
    "cadence_virtuoso": "skill",
    "synopsys_icc2":    "tcl",
    "klayout":          "py",
}


def compile_eu(
    host: str,
    template_name: str,
    args: dict[str, Any],
    language: str | None = None,
) -> str:
    """
    Render a Jinja2 EU template and return the compiled script string.

    Args:
        host:          EDA host identifier ("cadence_virtuoso", etc.)
        template_name: Base name of the template (without language extension)
        args:          Template variables (substituted into {{ ... }})
        language:      Override language extension (default: inferred from host)

    Returns:
        Rendered script string.

    Raises:
        FileNotFoundError: if the template file does not exist.
        jinja2.UndefinedError: if a required template variable is missing.
    """
    try:
        from jinja2 import Environment, FileSystemLoader, StrictUndefined
    except ImportError as e:
        raise RuntimeError("jinja2 not installed: pip install jinja2") from e

    lang = language or _LANG_EXT.get(host, "txt")
    template_path = _REGISTRY_ROOT / host / f"{template_name}.{lang}.j2"

    if not template_path.exists():
        raise FileNotFoundError(
            f"EU template not found: {template_path}\n"
            f"Available templates in {_REGISTRY_ROOT / host}:\n"
            + "\n".join(str(p) for p in (_REGISTRY_ROOT / host).glob("*.j2"))
            if (_REGISTRY_ROOT / host).exists() else "(directory does not exist)"
        )

    env = Environment(
        loader=FileSystemLoader(str(template_path.parent)),
        undefined=StrictUndefined,
        keep_trailing_newline=True,
    )
    template = env.get_template(template_path.name)
    rendered = template.render(**args)

    logger.info("[EU Compiler] Compiled %s/%s (%d chars)", host, template_name, len(rendered))
    return rendered


def list_templates(host: str | None = None) -> dict[str, list[str]]:
    """
    Return a dict of {host: [template_names]} for all registered templates.
    Optionally filter to a single host.
    """
    result: dict[str, list[str]] = {}
    hosts = [host] if host else [d.name for d in _REGISTRY_ROOT.iterdir() if d.is_dir()]
    for h in hosts:
        host_dir = _REGISTRY_ROOT / h
        if host_dir.exists():
            templates = [p.name.split(".")[0] for p in host_dir.glob("*.j2")]
            result[h] = sorted(set(templates))
    return result
